"""store scan_mode column with default camera_single

Revision ID: 1ca6f7f8dca9
Revises: 338a65081990
Create Date: 2026-04-27 02:31:17.396263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca6f7f8dca9'
down_revision = '338a65081990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_mode', sa.String(length=30), server_default='camera_single', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('scan_mode')

    # ### end Alembic commands ###
