"""user soft delete + partial unique index on (store_id, username) WHERE deleted_at IS NULL

Revision ID: 338a65081990
Revises: 046d493a25e6
Create Date: 2026-04-27 01:28:36.692829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338a65081990'
down_revision = '046d493a25e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_users_store_username'), type_='unique')
        batch_op.create_index('uq_users_store_username_active', ['store_id', 'username'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uq_users_store_username_active', sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.create_unique_constraint(batch_op.f('uq_users_store_username'), ['store_id', 'username'])
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
