"""add_cancels_to_employee_shifts

Revision ID: 628aef7c4bec
Revises: bdb94c63c9ed
Create Date: 2026-05-02 18:46:19.620921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628aef7c4bec'
down_revision = 'bdb94c63c9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_type', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('num_employees', sa.String(length=20), nullable=True),
    sa.Column('how_heard', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('store_count', sa.Integer(), nullable=True),
    sa.Column('current_process', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('plan_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('billing_email', sa.String(length=150), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cancelled_reason', sa.String(length=250), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('trial', 'active', 'expired', 'suspended', 'cancelled')", name='ck_subscription_status'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_days_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('employee_shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancels', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_index(batch_op.f('ix_employee_shifts_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('shift_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_books_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspended', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('owner_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_stores_created_by', 'users', ['created_by'], ['user_id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stores_created_by', type_='foreignkey')
        batch_op.drop_column('notes')
        batch_op.drop_column('created_by')
        batch_op.drop_column('owner_name')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('is_active')
        batch_op.drop_column('suspended')

    with op.batch_alter_table('shift_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_shift_books_uuid'), ['uuid'], unique=False)

    with op.batch_alter_table('employee_shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_employee_shifts_uuid'), ['uuid'], unique=False)
        batch_op.drop_column('cancels')

    with op.batch_alter_table('business_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.VARCHAR(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_business_days_uuid'), ['uuid'], unique=False)

    op.drop_table('audit_logs')
    op.drop_table('subscriptions')
    op.drop_table('contact_submissions')
    # ### end Alembic commands ###
