"""create slots table

Revision ID: 742fda53c0fe
Revises: 1bec05def4fd
Create Date: 2026-04-25 02:16:24.409596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742fda53c0fe'
down_revision = '1bec05def4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('slot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slot_name', sa.String(length=100), nullable=False),
    sa.Column('ticket_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('ticket_price IN (1.00, 2.00, 3.00, 5.00, 10.00, 20.00)', name='ck_slots_ticket_price'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slots_store_id'), ['store_id'], unique=False)
        batch_op.create_index('uq_slots_store_name_active', ['store_id', 'slot_name'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.drop_index('uq_slots_store_name_active', sqlite_where=sa.text('deleted_at IS NULL'), postgresql_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_slots_store_id'))

    op.drop_table('slots')
    # ### end Alembic commands ###
