"""create shift_books and shift_extra_sales tables

Revision ID: b018972e2e91
Revises: f9c6fec455df
Create Date: 2026-04-25 04:02:11.921600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b018972e2e91'
down_revision = 'f9c6fec455df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_books',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('scan_type', sa.String(length=10), nullable=False),
    sa.Column('start_at_scan', sa.Integer(), nullable=False),
    sa.Column('is_last_ticket', sa.Boolean(), nullable=False),
    sa.Column('scan_source', sa.String(length=25), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('scanned_by_user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("scan_source IN ('scanned', 'carried_forward', 'whole_book_sale', 'returned_to_vendor')", name='ck_shift_books_scan_source'),
    sa.CheckConstraint("scan_type IN ('open', 'close')", name='ck_shift_books_scan_type'),
    sa.ForeignKeyConstraint(['scanned_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_details.shift_id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.slot_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('shift_id', 'barcode', 'scan_type')
    )
    with op.batch_alter_table('shift_books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_books_store_id'), ['store_id'], unique=False)
        batch_op.create_index('ix_shift_books_store_scanned_at', ['store_id', 'scanned_at'], unique=False)

    op.create_table('shift_extra_sales',
    sa.Column('extra_sale_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('sale_type', sa.String(length=25), nullable=False),
    sa.Column('scanned_barcode', sa.String(length=100), nullable=False),
    sa.Column('ticket_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ticket_count', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('ticket_price IN (1.00, 2.00, 3.00, 5.00, 10.00, 20.00)', name='ck_shift_extra_sales_price'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift_details.shift_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('extra_sale_id')
    )
    with op.batch_alter_table('shift_extra_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_extra_sales_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shift_extra_sales_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_extra_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_extra_sales_store_id'))
        batch_op.drop_index(batch_op.f('ix_shift_extra_sales_shift_id'))

    op.drop_table('shift_extra_sales')
    with op.batch_alter_table('shift_books', schema=None) as batch_op:
        batch_op.drop_index('ix_shift_books_store_scanned_at')
        batch_op.drop_index(batch_op.f('ix_shift_books_store_id'))

    op.drop_table('shift_books')
    # ### end Alembic commands ###
