"""create books and book_assignment_history tables

Revision ID: e7accbd01967
Revises: 742fda53c0fe
Create Date: 2026-04-25 02:57:25.975017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7accbd01967'
down_revision = '742fda53c0fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('book_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_name', sa.String(length=150), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=False),
    sa.Column('static_code', sa.String(length=100), nullable=True),
    sa.Column('start_position', sa.Integer(), nullable=True),
    sa.Column('ticket_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('returned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('ticket_price IS NULL OR ticket_price IN (1.00, 2.00, 3.00, 5.00, 10.00, 20.00)', name='ck_books_ticket_price'),
    sa.ForeignKeyConstraint(['returned_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.slot_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.PrimaryKeyConstraint('book_id'),
    sa.UniqueConstraint('store_id', 'barcode', name='uq_books_store_barcode'),
    sa.UniqueConstraint('store_id', 'static_code', name='uq_books_store_static_code')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_static_code'), ['static_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_store_id'), ['store_id'], unique=False)

    op.create_table('book_assignment_history',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('ticket_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=False),
    sa.Column('unassigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('unassign_reason', sa.String(length=50), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("unassign_reason IS NULL OR unassign_reason IN ('reassigned', 'unassigned', 'sold', 'returned_to_vendor')", name='ck_bah_unassign_reason'),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.slot_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['unassigned_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    with op.batch_alter_table('book_assignment_history', schema=None) as batch_op:
        batch_op.create_index('ix_bah_book_unassigned', ['book_id', 'unassigned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_assignment_history_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_assignment_history_store_id'), ['store_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_assignment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_assignment_history_store_id'))
        batch_op.drop_index(batch_op.f('ix_book_assignment_history_book_id'))
        batch_op.drop_index('ix_bah_book_unassigned')

    op.drop_table('book_assignment_history')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_store_id'))
        batch_op.drop_index(batch_op.f('ix_books_static_code'))

    op.drop_table('books')
    # ### end Alembic commands ###
