"""create stores table

Revision ID: f6fda83d46fb
Revises: 
Create Date: 2026-04-25 00:13:44.247198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6fda83d46fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('store_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.String(length=150), nullable=False),
    sa.Column('store_code', sa.String(length=50), nullable=False),
    sa.Column('store_pin_hash', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('store_id'),
    sa.UniqueConstraint('store_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stores')
    # ### end Alembic commands ###
