"""create shift_details table

Revision ID: f9c6fec455df
Revises: e7accbd01967
Create Date: 2026-04-25 03:36:46.824209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c6fec455df'
down_revision = 'e7accbd01967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_details',
    sa.Column('shift_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shift_start_time', sa.DateTime(), nullable=False),
    sa.Column('shift_end_time', sa.DateTime(), nullable=True),
    sa.Column('cash_in_hand', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gross_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_out', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tickets_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shift_status', sa.String(length=20), nullable=True),
    sa.Column('is_shift_open', sa.Boolean(), nullable=False),
    sa.Column('main_shift_id', sa.Integer(), nullable=True),
    sa.Column('shift_number', sa.Integer(), nullable=False),
    sa.Column('opened_by_user_id', sa.Integer(), nullable=False),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('voided', sa.Boolean(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('voided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('main_shift_id IS NULL OR main_shift_id != shift_id', name='ck_no_self_reference'),
    sa.CheckConstraint('voided = 0 OR void_reason IS NOT NULL', name='ck_void_requires_reason'),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['main_shift_id'], ['shift_details.shift_id'], ),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('shift_id'),
    sa.UniqueConstraint('main_shift_id', 'shift_number', name='uq_subshift_number_per_main')
    )
    with op.batch_alter_table('shift_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_details_store_id'), ['store_id'], unique=False)
        batch_op.create_index('uq_one_open_main_shift_per_store', ['store_id'], unique=True, sqlite_where=sa.text('main_shift_id IS NULL AND is_shift_open = 1'), postgresql_where=sa.text('main_shift_id IS NULL AND is_shift_open = TRUE'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_details', schema=None) as batch_op:
        batch_op.drop_index('uq_one_open_main_shift_per_store', sqlite_where=sa.text('main_shift_id IS NULL AND is_shift_open = 1'), postgresql_where=sa.text('main_shift_id IS NULL AND is_shift_open = TRUE'))
        batch_op.drop_index(batch_op.f('ix_shift_details_store_id'))

    op.drop_table('shift_details')
    # ### end Alembic commands ###
